# for a complete reference, visit
# https://github.com/Macchina-CLI/macchina/wiki/Theme-Documentation

hide_ascii = false
prefer_small_ascii = false
spacing = 2
padding = 0
separator = "::"
key_color = "Cyan"
separator_color = "Blue"
palette = "Full"

[bar]
glyph = "o"
symbol_open = "("
symbol_close = ")"
visible = false

[box]
title = " Info "
visible = true

[box.inner_margin]
x = 2
y = 1

[custom_ascii]
color = "Cyan"
path = "~/.dots/scripts/storage/nixos.txt"

[randomize]
key_color = false
separator_color = false

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
local_ip = "IP"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = "CPU Load"
cpu = "CPU"
